import { useEffect,useSyncExternalStore } from 'react'; import { engine } from '@/data/engine'; import type { DataMode,MarketQuotesResponse,ProviderStatus,RemoteQuotePatch } from '@/shared/api'; import { ClientApiError, apiFetch } from './apiClient.js';
export interface MarketRuntimeStatus{readonly enabled:boolean;readonly phase:'idle'|'loading'|'ready'|'degraded';readonly mode:DataMode;readonly label:string;readonly activeSymbols:readonly string[];readonly providers:readonly ProviderStatus[];readonly warnings:readonly string[];readonly lastAttemptAt?:string;readonly lastSuccessAt?:string;readonly asOfISO?:string;readonly requestId?:string;readonly error?:string}
const disabled=import.meta.env.MODE==='test'||String(import.meta.env.VITE_ENABLE_LIVE_DATA??'true').toLowerCase()==='false';const POLL=Math.max(5000,Math.min(300000,Number(import.meta.env.VITE_MARKET_POLL_MS??20000)||20000));const registrations=new Map<string,number>();const listeners=new Set<()=>void>();let timer:number|null=null;let inflight:Promise<void>|null=null;let suspended=false;let offset=0;let verified=false;let state:MarketRuntimeStatus=Object.freeze({enabled:!disabled,phase:'idle',mode:'mock',label:disabled?'모의 데이터':'실데이터 연결 대기',activeSymbols:Object.freeze([]),providers:Object.freeze([]),warnings:Object.freeze([])});
function label(mode:DataMode):string{return({live:'실시간',delayed:'지연 시세',snapshot:'공급자 스냅숏',mock:'모의 데이터',fallback:'로컬 폴백',mixed:'혼합 데이터',stale:'최근 검증값 유지'} as Record<DataMode,string>)[mode];}
function emit(next:MarketRuntimeStatus){state=Object.freeze({...next,activeSymbols:Object.freeze([...next.activeSymbols]),providers:Object.freeze([...next.providers]),warnings:Object.freeze([...next.warnings])});for(const l of listeners)l();}
function symbols():readonly string[]{return Object.freeze([...registrations.entries()].filter(([,count])=>count>0).map(([s])=>s).sort());}
function chunk(all:readonly string[]):readonly string[]{if(all.length<=20)return all;const start=offset%all.length;const out:string[]=[];for(let i=0;i<20;i++)out.push(all[(start+i)%all.length]);offset=(start+20)%all.length;return out;}
const providerPatch=(p:RemoteQuotePatch)=>p.provenance.source!=='local-simulation';
async function poll():Promise<void>{if(disabled||suspended||inflight||(typeof document!=='undefined'&&document.hidden))return;const all=symbols();if(!all.length)return;const selected=chunk(all);const attempted=new Date().toISOString();emit({...state,phase:state.lastSuccessAt?state.phase:'loading',activeSymbols:all,lastAttemptAt:attempted});inflight=(async()=>{try{const response=await apiFetch<MarketQuotesResponse>(`/api/market/quotes?symbols=${encodeURIComponent(selected.join(','))}`);const remote=response.quotes.filter(providerPatch);if(remote.some((p)=>['live','delayed','snapshot'].includes(p.provenance.mode))){verified=true;engine.setExternalFeedActive(true);}else if(!verified)engine.setExternalFeedActive(false);const accepted=response.quotes.filter((p)=>providerPatch(p)||(!verified&&engine.getQuote(p.symbol)?.provenance.source==='local-simulation'));if(accepted.length)engine.applyExternalQuotes(accepted);if(verified&&!remote.length){emit({enabled:true,phase:'degraded',mode:'stale',label:label('stale'),activeSymbols:all,providers:response.providers,warnings:Object.freeze([...response.warnings,'최근 검증 시세를 유지하고 합성 폴백으로 덮어쓰지 않았습니다.']),lastAttemptAt:attempted,lastSuccessAt:state.lastSuccessAt,asOfISO:state.asOfISO,requestId:response.requestId});return;}const degraded=response.warnings.length>0||['fallback','mixed'].includes(response.mode);const asOf=remote.map((p)=>p.provenance.providerTimestamp).sort().at(-1)??state.asOfISO;emit({enabled:true,phase:degraded?'degraded':'ready',mode:response.mode,label:label(response.mode),activeSymbols:all,providers:response.providers,warnings:response.warnings,lastAttemptAt:attempted,lastSuccessAt:response.generatedAt,asOfISO:asOf,requestId:response.requestId});}catch(error){const unconfigured=error instanceof ClientApiError&&error.code==='MARKET_DATA_UNAVAILABLE';if(unconfigured)stopPolling();emit({...state,enabled:true,phase:'degraded',mode:verified?'stale':'fallback',label:verified?label('stale'):'로컬 폴백',activeSymbols:all,warnings:Object.freeze([unconfigured?'시장 데이터 공급자가 설정되지 않아 폴링을 중단하고 P1 로컬 엔진을 유지합니다. 새로고침하거나 시스템 상태에서 다시 점검하면 재개합니다.':verified?'API 실패로 최근 검증 시세를 유지합니다.':'API 실패로 P1 로컬 엔진을 유지합니다.']),lastAttemptAt:attempted,error:error instanceof Error?error.message:String(error)});}finally{inflight=null;}})();await inflight;}
/** Clears the interval without touching registrations — `maybeStop` is for the last unmount. */
function clearTimer(){if(timer===null||typeof window==='undefined')return;window.clearInterval(timer);timer=null;window.removeEventListener('online',poll);document.removeEventListener('visibilitychange',poll);}
/**
 * The server reports `MARKET_DATA_UNAVAILABLE` when no provider is configured. That is a
 * deployment condition, not a transient failure, so retrying every 20s only floods the console
 * with 503s that can never succeed — the header badge already reads 로컬 폴백. Stop, and let an
 * explicit `refreshMarketData()` (the 시스템 상태 다시 점검 button) or a reload resume.
 */
function stopPolling(){suspended=true;clearTimer();}
function ensure(){if(disabled||suspended||timer!==null||typeof window==='undefined')return;timer=window.setInterval(()=>void poll(),POLL);window.addEventListener('online',poll);document.addEventListener('visibilitychange',poll);void poll();}
function maybeStop(){if(registrations.size)return;clearTimer();}
export function registerLiveSymbols(values:readonly string[]):()=>void{const normalized=[...new Set(values.filter(Boolean))];for(const s of normalized)registrations.set(s,(registrations.get(s)??0)+1);emit({...state,activeSymbols:symbols()});ensure();if(!disabled&&!suspended)void poll();return()=>{for(const s of normalized){const next=(registrations.get(s)??1)-1;if(next<=0)registrations.delete(s);else registrations.set(s,next);}emit({...state,activeSymbols:symbols()});maybeStop();};}
export function useLiveSymbols(values:readonly string[]):void{const key=values.join(',');useEffect(()=>registerLiveSymbols(values),[key]);}
export function subscribeMarketRuntime(l:()=>void):()=>void{listeners.add(l);return()=>listeners.delete(l);}
export function marketRuntimeSnapshot():MarketRuntimeStatus{return state;}
export function useMarketRuntimeStatus():MarketRuntimeStatus{return useSyncExternalStore(subscribeMarketRuntime,marketRuntimeSnapshot,marketRuntimeSnapshot);}
/** Explicit user action: clear any suspension and resume the periodic loop. */
export function refreshMarketData():Promise<void>{suspended=false;ensure();return poll();}
/** Test seam: reset module state between cases. */
export function __resetMarketRuntime():void{suspended=false;verified=false;clearTimer();registrations.clear();}
