import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';

const directory = new URL('../supabase/migrations/', import.meta.url);
const files = readdirSync(directory).filter((name) => name.endsWith('.sql')).sort();
assert.deepEqual(files, [
  '202607120001_p2_cloud.sql',
  '202607120002_p3_operations.sql',
  '202607120003_p3_hardening.sql',
  '202607120004_p4_portfolio_intelligence.sql',
  '202607130001_p6_target_allocations.sql',
  '202607130002_p7_rebalance_workflow.sql',
  '202607140001_p8_goal_contributions.sql',
  '202607140002_p9_order_cost_optimization.sql',
  '202608050001_p10_monitor_rules.sql',
]);
const cloudSql = readFileSync(new URL(files[0]!, directory), 'utf8').toLowerCase();
const operationsSql = readFileSync(new URL(files[1]!, directory), 'utf8').toLowerCase();
const hardeningSql = readFileSync(new URL(files[2]!, directory), 'utf8').toLowerCase();
const portfolioSql = readFileSync(new URL(files[3]!, directory), 'utf8').toLowerCase();
const allocationSql = readFileSync(new URL(files[4]!, directory), 'utf8').toLowerCase();
const rebalanceSql = readFileSync(new URL(files[5]!, directory), 'utf8').toLowerCase();
const contributionSql = readFileSync(new URL(files[6]!, directory), 'utf8').toLowerCase();
const orderCostSql = readFileSync(new URL(files[7]!, directory), 'utf8').toLowerCase();
// files[8] (P10) was previously left out of this slice entirely, so this script's
// `sql.includes(...)` contract checks and the anon/authenticated grant regex below never
// scanned it at all -- it returned PASS even when the P10 file did not parse. Every listed
// migration is now included.
const monitorSql = readFileSync(new URL(files[8]!, directory), 'utf8').toLowerCase();
const sql = `${cloudSql}\n${operationsSql}\n${hardeningSql}\n${portfolioSql}\n${allocationSql}\n${rebalanceSql}\n${contributionSql}\n${orderCostSql}\n${monitorSql}`;
for (const contract of [
  'claim_due_price_alerts',
  'for update skip locked',
  'evaluation_lease_until',
  'complete_price_alert_observation',
  'release_price_alert_evaluation',
  'system_heartbeats',
  'market_observations',
  'market_observations_dedupe_idx',
  'data_quality_incidents',
  'provider_health_snapshots',
  'ops_action_idempotency',
  'claim_ops_action',
  'complete_ops_action',
  'release_ops_action',
  'ops_audit_log',
  'release_gate_runs',
  'market_slo_evidence',
  'retry_failed_alert_deliveries',
  'prune_finance_operational_data',
  'claim_price_alert_and_enqueue',
  'claim_ops_action',
  'complete_ops_action',
  'release_ops_action',
  'ops_action_idempotency_status_check',
  'grant execute',
  'to service_role',
  'append_portfolio_transaction',
  'reverse_latest_portfolio_transaction',
  'pg_advisory_xact_lock',
  'portfolio_snapshots',
  'portfolios_snapshot_fairness_idx',
  'trade time precedes latest active transaction',
  'old.name is distinct from new.name',
  'investment_theses',
  'revoke insert, update, delete on public.portfolio_transactions from service_role',
  'portfolio_allocation_policies',
  'portfolio_allocation_targets',
  'replace_portfolio_allocation_policy',
  'target percentages must total 100',
  'portfolio_rebalance_runs',
  'portfolio_rebalance_items',
  'portfolio_rebalance_fills',
  'portfolio_rebalance_events',
  'portfolio_rebalance_deliveries',
  'portfolio_rebalance_runs_one_open_idx',
  'create_portfolio_rebalance_run',
  'transition_portfolio_rebalance_run',
  'complete_portfolio_rebalance_run',
  'claim_due_portfolio_rebalance_deliveries',
  'expire_portfolio_rebalance_runs',
  'audit_rebalance_execution_reversal',
  'execution_reversed',
  'rebalance_email_enabled',
  'rebalance_push_enabled',
  'portfolio_goals',
  'plan_kind',
  'upsert_portfolio_goal',
  'create_portfolio_contribution_run',
  'transition_portfolio_contribution_run',
  'complete_portfolio_contribution_run',
  'portfolio_contribution_runs_cycle_idx',
  'replace_portfolio_allocation_policy_p9',
  'commission_fixed_usd',
  'sell_transaction_tax_bps',
  'capital_gains_tax_pct',
  'max_cost_pct',
  'cost_model_version',
  'cost_policy_snapshot',
  'requested_trade_value',
  'optimization_decision',
  'estimated_costs',
  'estimated_cost_basis',
  'tax_lot_snapshot',
  'actual_costs',
  'create_portfolio_rebalance_run_p8',
  'complete_portfolio_rebalance_run_p8',
  'create_portfolio_contribution_run_p8',
  'complete_portfolio_contribution_run_p8',
  'apply_p9_plan_costs',
  'validate_p9_actual_costs',
  'persist_p9_actual_costs',
  'monitor_rules',
  'monitor_digests',
  'monitor_breaches',
  'monitor_digest_deliveries',
  'validate_monitor_rule_spec',
  'upsert_monitor_rule',
  'delete_monitor_rule',
  'claim_due_monitor_rules',
  'record_monitor_evaluation',
  'open_monitor_digest',
  'append_monitor_breach',
  'enqueue_monitor_digest_deliveries',
  'claim_due_monitor_digest_deliveries',
  'mark_monitor_digest_delivery_sent',
  'mark_monitor_digest_delivery_failure',
  'mark_monitor_digest_delivery_disabled',
]) assert.ok(sql.includes(contract), `missing migration contract: ${contract}`);
assert.ok(!/grant\s+(insert|update|delete|all)[\s\S]{0,120}\s+to\s+(anon|authenticated)/i.test(sql));
console.log(JSON.stringify({
  migrations: files,
  fairScheduler: true,
  atomicAlertDelivery: true,
  leasedOpsIdempotency: true,
  opsLedger: true,
  privilegedMutations: true,
  appendOnlyPortfolioLedger: true,
  portfolioSnapshots: true,
  targetAllocations: true,
  durableRebalanceWorkflow: true,
  rebalanceDeliveryQueue: true,
  goalContributionPlanning: true,
  orderCostOptimization: true,
  immutableCostEvidence: true,
  result: 'PASS',
}, null, 2));
