-- Perplexity Finance v1.5.0 P4 portfolio intelligence.
-- Append-only portfolio ledger, immutable reversals, snapshots and research theses.

create table if not exists public.portfolios (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  base_currency text not null default 'USD' check (base_currency = 'USD'),
  status text not null default 'active' check (status in ('active', 'archived')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  last_snapshot_attempt_at timestamptz
);
alter table public.portfolios add column if not exists last_snapshot_attempt_at timestamptz;
create index if not exists portfolios_user_status_idx on public.portfolios(user_id, status, created_at);
create index if not exists portfolios_snapshot_fairness_idx on public.portfolios(status, last_snapshot_attempt_at nulls first);

drop trigger if exists portfolios_set_updated_at on public.portfolios;
create trigger portfolios_set_updated_at
  before update on public.portfolios
  for each row
  when (
    old.name is distinct from new.name
    or old.base_currency is distinct from new.base_currency
    or old.status is distinct from new.status
  )
  execute function public.set_updated_at();

create table if not exists public.portfolio_transactions (
  id uuid primary key default gen_random_uuid(),
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('deposit', 'withdrawal', 'buy', 'sell', 'dividend', 'fee', 'reversal')),
  symbol text,
  quantity numeric(28, 12) not null default 0 check (quantity >= 0),
  price numeric(28, 8) not null default 0 check (price >= 0),
  cash_amount numeric(28, 8) not null default 0 check (cash_amount >= 0),
  fees numeric(28, 8) not null default 0 check (fees >= 0),
  trade_at timestamptz not null,
  note text check (note is null or char_length(note) <= 500),
  reversal_of uuid references public.portfolio_transactions(id),
  idempotency_key text not null check (char_length(idempotency_key) between 8 and 128),
  created_at timestamptz not null default timezone('utc', now()),
  constraint portfolio_transactions_shape_check check (
    (
      kind in ('buy', 'sell')
      and symbol is not null
      and symbol = upper(symbol)
      and char_length(symbol) between 1 and 20
      and quantity > 0
      and price > 0
      and cash_amount = 0
      and reversal_of is null
    )
    or (
      kind in ('deposit', 'withdrawal', 'dividend', 'fee')
      and quantity = 0
      and price = 0
      and cash_amount > 0
      and reversal_of is null
      and (symbol is null or (symbol = upper(symbol) and char_length(symbol) between 1 and 20))
    )
    or (
      kind = 'reversal'
      and symbol is null
      and quantity = 0
      and price = 0
      and cash_amount = 0
      and fees = 0
      and reversal_of is not null
    )
  ),
  unique(user_id, idempotency_key)
);
create unique index if not exists portfolio_transactions_one_reversal_idx
  on public.portfolio_transactions(reversal_of) where reversal_of is not null;
create index if not exists portfolio_transactions_ledger_idx
  on public.portfolio_transactions(portfolio_id, trade_at, created_at, id);
create index if not exists portfolio_transactions_symbol_idx
  on public.portfolio_transactions(portfolio_id, symbol) where symbol is not null;

create table if not exists public.portfolio_snapshots (
  id bigint generated by default as identity primary key,
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  captured_at timestamptz not null default timezone('utc', now()),
  capture_bucket timestamptz not null,
  as_of timestamptz not null,
  total_value numeric(28, 8) not null,
  cash_balance numeric(28, 8) not null,
  market_value numeric(28, 8) not null,
  net_contributions numeric(28, 8) not null,
  total_return numeric(28, 8) not null,
  valuation_quality text not null check (valuation_quality in ('verified', 'mixed', 'estimated', 'unpriced')),
  metrics jsonb not null default '{}'::jsonb,
  holdings jsonb not null default '[]'::jsonb,
  unique(portfolio_id, capture_bucket)
);
create index if not exists portfolio_snapshots_user_idx
  on public.portfolio_snapshots(user_id, portfolio_id, captured_at desc);

create table if not exists public.investment_theses (
  id uuid primary key default gen_random_uuid(),
  portfolio_id uuid references public.portfolios(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null check (symbol = upper(symbol) and char_length(symbol) between 1 and 20),
  title text not null check (char_length(title) between 1 and 120),
  thesis text not null check (char_length(thesis) between 1 and 6000),
  bull_case text not null default '' check (char_length(bull_case) <= 4000),
  bear_case text not null default '' check (char_length(bear_case) <= 4000),
  catalysts text[] not null default '{}',
  invalidation text not null default '' check (char_length(invalidation) <= 3000),
  target_price numeric(28, 8) check (target_price is null or target_price > 0),
  confidence smallint not null default 50 check (confidence between 0 and 100),
  status text not null default 'watching' check (status in ('watching', 'active', 'invalidated', 'realized', 'archived')),
  evidence jsonb not null default '[]'::jsonb,
  evidence_hash text check (evidence_hash is null or char_length(evidence_hash) between 8 and 128),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);
create index if not exists investment_theses_user_idx
  on public.investment_theses(user_id, status, updated_at desc);
create index if not exists investment_theses_symbol_idx
  on public.investment_theses(user_id, symbol, updated_at desc);

drop trigger if exists investment_theses_set_updated_at on public.investment_theses;
create trigger investment_theses_set_updated_at
  before update on public.investment_theses
  for each row execute function public.set_updated_at();

alter table public.portfolios enable row level security;
alter table public.portfolio_transactions enable row level security;
alter table public.portfolio_snapshots enable row level security;
alter table public.investment_theses enable row level security;

-- Authenticated clients can read only their own rows. All mutations pass through
-- validated Vercel API routes and the service role.
drop policy if exists portfolios_select_own on public.portfolios;
create policy portfolios_select_own on public.portfolios for select to authenticated
  using (auth.uid() = user_id);
drop policy if exists portfolio_transactions_select_own on public.portfolio_transactions;
create policy portfolio_transactions_select_own on public.portfolio_transactions for select to authenticated
  using (auth.uid() = user_id);
drop policy if exists portfolio_snapshots_select_own on public.portfolio_snapshots;
create policy portfolio_snapshots_select_own on public.portfolio_snapshots for select to authenticated
  using (auth.uid() = user_id);
drop policy if exists investment_theses_select_own on public.investment_theses;
create policy investment_theses_select_own on public.investment_theses for select to authenticated
  using (auth.uid() = user_id);

grant select on public.portfolios, public.portfolio_transactions, public.portfolio_snapshots, public.investment_theses to authenticated;
revoke all on public.portfolios, public.portfolio_transactions, public.portfolio_snapshots, public.investment_theses from anon;

revoke insert, update, delete on public.portfolios from authenticated;
revoke insert, update, delete on public.portfolio_transactions from authenticated;
-- The service role can read transactions but cannot bypass the append-only RPC boundary.
revoke insert, update, delete on public.portfolio_transactions from service_role;
grant select on public.portfolio_transactions to service_role;
revoke insert, update, delete on public.portfolio_snapshots from authenticated;
revoke insert, update, delete on public.investment_theses from authenticated;

create or replace function public.portfolio_current_cash(p_portfolio_id uuid)
returns numeric
language sql
stable
security definer
set search_path = public
as $$
  with active as (
    select t.*
    from public.portfolio_transactions t
    where t.portfolio_id = p_portfolio_id
      and t.kind <> 'reversal'
      and not exists (
        select 1 from public.portfolio_transactions r where r.reversal_of = t.id
      )
  )
  select coalesce(sum(case
    when kind = 'deposit' then cash_amount
    when kind = 'withdrawal' then -cash_amount
    when kind = 'buy' then -(quantity * price + fees)
    when kind = 'sell' then quantity * price - fees
    when kind = 'dividend' then cash_amount
    when kind = 'fee' then -cash_amount
    else 0
  end), 0)
  from active;
$$;
revoke all on function public.portfolio_current_cash(uuid) from public;
grant execute on function public.portfolio_current_cash(uuid) to service_role;

create or replace function public.portfolio_current_quantity(p_portfolio_id uuid, p_symbol text)
returns numeric
language sql
stable
security definer
set search_path = public
as $$
  with active as (
    select t.*
    from public.portfolio_transactions t
    where t.portfolio_id = p_portfolio_id
      and t.symbol = upper(p_symbol)
      and t.kind in ('buy', 'sell')
      and not exists (
        select 1 from public.portfolio_transactions r where r.reversal_of = t.id
      )
  )
  select coalesce(sum(case when kind = 'buy' then quantity else -quantity end), 0)
  from active;
$$;
revoke all on function public.portfolio_current_quantity(uuid, text) from public;
grant execute on function public.portfolio_current_quantity(uuid, text) to service_role;

create or replace function public.append_portfolio_transaction(
  p_user_id uuid,
  p_portfolio_id uuid,
  p_idempotency_key text,
  p_kind text,
  p_symbol text,
  p_quantity numeric,
  p_price numeric,
  p_cash_amount numeric,
  p_fees numeric,
  p_trade_at timestamptz,
  p_note text
) returns setof public.portfolio_transactions
language plpgsql
security definer
set search_path = public
as $$
declare
  owned public.portfolios%rowtype;
  existing public.portfolio_transactions%rowtype;
  inserted public.portfolio_transactions%rowtype;
  available_cash numeric;
  available_quantity numeric;
  normalized_symbol text;
begin
  if p_idempotency_key is null or char_length(p_idempotency_key) < 8 or char_length(p_idempotency_key) > 128
    or p_idempotency_key !~ '^[A-Za-z0-9._:-]+$' then
    raise exception 'invalid idempotency key' using errcode = '22023';
  end if;

  -- Serialize the same user/key across serverless instances and portfolios before
  -- reading the idempotency record. This turns concurrent retries into replay.
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':' || p_idempotency_key, 0));

  select * into existing from public.portfolio_transactions
  where user_id = p_user_id and idempotency_key = p_idempotency_key;
  if found then
    return next existing;
    return;
  end if;

  select * into owned from public.portfolios
  where id = p_portfolio_id and user_id = p_user_id and status = 'active'
  for update;
  if not found then raise exception 'portfolio not found' using errcode = 'P0002'; end if;

  normalized_symbol := nullif(upper(trim(coalesce(p_symbol, ''))), '');
  if p_kind not in ('deposit', 'withdrawal', 'buy', 'sell', 'dividend', 'fee') then
    raise exception 'invalid transaction kind' using errcode = '22023';
  end if;
  if p_trade_at is null or p_trade_at > timezone('utc', now()) + interval '5 minutes' then
    raise exception 'invalid trade time' using errcode = '22023';
  end if;
  if exists (
    select 1
    from public.portfolio_transactions later
    where later.portfolio_id = p_portfolio_id
      and later.kind <> 'reversal'
      and not exists (select 1 from public.portfolio_transactions r where r.reversal_of = later.id)
      and later.trade_at > p_trade_at
  ) then
    raise exception 'trade time precedes latest active transaction' using errcode = 'P0001';
  end if;
  if coalesce(p_quantity, 0) < 0 or coalesce(p_price, 0) < 0
    or coalesce(p_cash_amount, 0) < 0 or coalesce(p_fees, 0) < 0 then
    raise exception 'negative values are not allowed' using errcode = '22023';
  end if;

  available_cash := public.portfolio_current_cash(p_portfolio_id);
  if p_kind = 'buy' then
    if normalized_symbol is null or p_quantity <= 0 or p_price <= 0 then
      raise exception 'buy requires symbol, quantity and price' using errcode = '22023';
    end if;
    if available_cash + 0.00000001 < p_quantity * p_price + coalesce(p_fees, 0) then
      raise exception 'insufficient cash' using errcode = 'P0001';
    end if;
  elsif p_kind = 'sell' then
    if normalized_symbol is null or p_quantity <= 0 or p_price <= 0 then
      raise exception 'sell requires symbol, quantity and price' using errcode = '22023';
    end if;
    available_quantity := public.portfolio_current_quantity(p_portfolio_id, normalized_symbol);
    if available_quantity + 0.000000000001 < p_quantity then
      raise exception 'insufficient position' using errcode = 'P0001';
    end if;
  elsif p_kind in ('withdrawal', 'fee') then
    if p_cash_amount <= 0 then raise exception 'cash amount required' using errcode = '22023'; end if;
    if available_cash + 0.00000001 < p_cash_amount then
      raise exception 'insufficient cash' using errcode = 'P0001';
    end if;
  elsif p_kind in ('deposit', 'dividend') and p_cash_amount <= 0 then
    raise exception 'cash amount required' using errcode = '22023';
  end if;

  insert into public.portfolio_transactions(
    portfolio_id, user_id, kind, symbol, quantity, price, cash_amount, fees,
    trade_at, note, idempotency_key
  ) values (
    p_portfolio_id, p_user_id, p_kind, normalized_symbol,
    case when p_kind in ('buy', 'sell') then p_quantity else 0 end,
    case when p_kind in ('buy', 'sell') then p_price else 0 end,
    case when p_kind in ('deposit', 'withdrawal', 'dividend', 'fee') then p_cash_amount else 0 end,
    case when p_kind in ('buy', 'sell') then coalesce(p_fees, 0) else 0 end,
    p_trade_at, nullif(trim(coalesce(p_note, '')), ''), p_idempotency_key
  ) returning * into inserted;

  update public.portfolios set updated_at = timezone('utc', now()) where id = p_portfolio_id;
  return next inserted;
end;
$$;
revoke all on function public.append_portfolio_transaction(uuid, uuid, text, text, text, numeric, numeric, numeric, numeric, timestamptz, text) from public;
grant execute on function public.append_portfolio_transaction(uuid, uuid, text, text, text, numeric, numeric, numeric, numeric, timestamptz, text) to service_role;

create or replace function public.reverse_latest_portfolio_transaction(
  p_user_id uuid,
  p_portfolio_id uuid,
  p_transaction_id uuid,
  p_idempotency_key text,
  p_note text
) returns setof public.portfolio_transactions
language plpgsql
security definer
set search_path = public
as $$
declare
  owned public.portfolios%rowtype;
  target public.portfolio_transactions%rowtype;
  existing public.portfolio_transactions%rowtype;
  inserted public.portfolio_transactions%rowtype;
begin
  if p_idempotency_key is null or char_length(p_idempotency_key) < 8 or char_length(p_idempotency_key) > 128
    or p_idempotency_key !~ '^[A-Za-z0-9._:-]+$' then
    raise exception 'invalid idempotency key' using errcode = '22023';
  end if;

  -- Serialize the same user/key across serverless instances and portfolios before
  -- reading the idempotency record. This turns concurrent retries into replay.
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':' || p_idempotency_key, 0));

  select * into existing from public.portfolio_transactions
  where user_id = p_user_id and idempotency_key = p_idempotency_key;
  if found then
    return next existing;
    return;
  end if;

  select * into owned from public.portfolios
  where id = p_portfolio_id and user_id = p_user_id and status = 'active'
  for update;
  if not found then raise exception 'portfolio not found' using errcode = 'P0002'; end if;

  select * into target from public.portfolio_transactions
  where id = p_transaction_id
    and portfolio_id = p_portfolio_id
    and user_id = p_user_id
    and kind <> 'reversal'
    and not exists (select 1 from public.portfolio_transactions r where r.reversal_of = p_transaction_id)
  for update;
  if not found then raise exception 'transaction not found or already reversed' using errcode = 'P0002'; end if;

  if exists (
    select 1 from public.portfolio_transactions later
    where later.portfolio_id = p_portfolio_id
      and later.kind <> 'reversal'
      and not exists (select 1 from public.portfolio_transactions r where r.reversal_of = later.id)
      and (later.trade_at, later.created_at, later.id) > (target.trade_at, target.created_at, target.id)
  ) then
    raise exception 'only the latest active transaction can be reversed' using errcode = 'P0001';
  end if;

  insert into public.portfolio_transactions(
    portfolio_id, user_id, kind, quantity, price, cash_amount, fees,
    trade_at, note, reversal_of, idempotency_key
  ) values (
    p_portfolio_id, p_user_id, 'reversal', 0, 0, 0, 0,
    timezone('utc', now()), nullif(trim(coalesce(p_note, '')), ''), target.id, p_idempotency_key
  ) returning * into inserted;

  update public.portfolios set updated_at = timezone('utc', now()) where id = p_portfolio_id;
  return next inserted;
end;
$$;
revoke all on function public.reverse_latest_portfolio_transaction(uuid, uuid, uuid, text, text) from public;
grant execute on function public.reverse_latest_portfolio_transaction(uuid, uuid, uuid, text, text) to service_role;

DO $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'portfolios'
  ) then alter publication supabase_realtime add table public.portfolios; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'portfolio_transactions'
  ) then alter publication supabase_realtime add table public.portfolio_transactions; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'investment_theses'
  ) then alter publication supabase_realtime add table public.investment_theses; end if;
end;
$$;
